-- Seed: catálogo maestro COCATO
-- Ejecutar después de sql/create_productos.sql

TRUNCATE TABLE public.productos;

INSERT INTO public.productos (
  nombre,
  categoria,
  subcategoria,
  unidad,
  precio_kg,
  activo,
  orden
) VALUES

-- =========================
-- RES · CORTES
-- =========================
('Maciza', 'Res', 'Corte', 'kg', 0, true, 101),
('Diezmillo', 'Res', 'Corte', 'kg', 0, true, 102),
('Espinazo', 'Res', 'Corte', 'kg', 0, true, 103),
('Costilla', 'Res', 'Corte', 'kg', 0, true, 104),
('Retazo', 'Res', 'Corte', 'kg', 0, true, 105),
('Suadero', 'Res', 'Corte', 'kg', 0, true, 106),
('Arrachera', 'Res', 'Corte', 'kg', 0, true, 107),
('Sirloin', 'Res', 'Corte', 'kg', 0, true, 108),
('Rib Eye', 'Res', 'Corte', 'kg', 0, true, 109),
('T-Bone', 'Res', 'Corte', 'kg', 0, true, 110),
('Porterhouse', 'Res', 'Corte', 'kg', 0, true, 111),
('Pulpa blanca', 'Res', 'Corte', 'kg', 0, true, 112),
('Pulpa negra', 'Res', 'Corte', 'kg', 0, true, 113),
('Aguayón', 'Res', 'Corte', 'kg', 0, true, 114),
('Aguayón norteño', 'Res', 'Corte', 'kg', 0, true, 115),
('Cuete', 'Res', 'Corte', 'kg', 0, true, 116),
('Bola', 'Res', 'Corte', 'kg', 0, true, 117),
('Pecho', 'Res', 'Corte', 'kg', 0, true, 118),
('Falda', 'Res', 'Corte', 'kg', 0, true, 119),
('Chambarete', 'Res', 'Corte', 'kg', 0, true, 120),
('Picaña', 'Res', 'Corte', 'kg', 0, true, 121),
('Filete', 'Res', 'Corte', 'kg', 0, true, 122),
('Entrecote', 'Res', 'Corte', 'kg', 0, true, 123),
('Milanesa', 'Res', 'Corte', 'kg', 0, true, 124),
('Molida especial', 'Res', 'Corte', 'kg', 0, true, 125),
('Molida corriente', 'Res', 'Corte', 'kg', 0, true, 126),
('Molida 90/10', 'Res', 'Corte', 'kg', 0, true, 127),
('Molida 80/20', 'Res', 'Corte', 'kg', 0, true, 128),
('Aguja', 'Res', 'Corte', 'kg', 0, true, 129),
('Cortadillo', 'Res', 'Corte', 'kg', 0, true, 130),
('Bistec de res', 'Res', 'Corte', 'kg', 0, true, 131),
('Bistec de bola', 'Res', 'Corte', 'kg', 0, true, 132),
('Bistec de pulpa negra', 'Res', 'Corte', 'kg', 0, true, 133),
('Churrasco', 'Res', 'Corte', 'kg', 0, true, 134),
('New York', 'Res', 'Corte', 'kg', 0, true, 135),
('Chuleta de res', 'Res', 'Corte', 'kg', 0, true, 136),
('Carne para asar', 'Res', 'Corte', 'kg', 0, true, 137),
('Carne para deshebrar', 'Res', 'Corte', 'kg', 0, true, 138),
('Carne para guisar', 'Res', 'Corte', 'kg', 0, true, 139),
('Carne para taquitos', 'Res', 'Corte', 'kg', 0, true, 140),
('Fajitas de res', 'Res', 'Corte', 'kg', 0, true, 141),
('Tapa', 'Res', 'Corte', 'kg', 0, true, 142),
('Cadera', 'Res', 'Corte', 'kg', 0, true, 143),
('Guisador', 'Res', 'Corte', 'kg', 0, true, 144),
('Cachete', 'Res', 'Corte', 'kg', 0, true, 145),
('Rabo', 'Res', 'Corte', 'kg', 0, true, 146),
('Cecina natural', 'Res', 'Corte', 'kg', 0, true, 147),
('Colita de cuadril', 'Res', 'Corte', 'kg', 0, true, 148),
('Vacío', 'Res', 'Corte', 'kg', 0, true, 149),
('Asador', 'Res', 'Corte', 'kg', 0, true, 150),
('Top sirloin', 'Res', 'Corte', 'kg', 0, true, 151),
('Short rib', 'Res', 'Corte', 'kg', 0, true, 152),
('Costilla de res', 'Res', 'Corte', 'kg', 0, true, 153),
('Molida 70/30', 'Res', 'Corte', 'kg', 0, true, 154),
('Molida para hamburguesa', 'Res', 'Corte', 'kg', 0, true, 155),
('Carne molida especial', 'Res', 'Corte', 'kg', 0, true, 156),
('Deshebrada cruda', 'Res', 'Corte', 'kg', 0, true, 157),
('Carne para barbacoa', 'Res', 'Corte', 'kg', 0, true, 158),
('Carne para birria', 'Res', 'Corte', 'kg', 0, true, 159),
('Carne para consomé', 'Res', 'Corte', 'kg', 0, true, 160),
('Carne para caldo', 'Res', 'Corte', 'kg', 0, true, 161),
('Bistec ranchero', 'Res', 'Corte', 'kg', 0, true, 162),
('Bistec suizo', 'Res', 'Corte', 'kg', 0, true, 163),
('Bistec empanizado', 'Res', 'Corte', 'kg', 0, true, 164),
('Carne para milanesa', 'Res', 'Corte', 'kg', 0, true, 165),

-- =========================
-- RES · HUESOS
-- =========================
('Hueso para caldo', 'Res', 'Huesos', 'kg', 0, true, 251),
('Hueso carnudo', 'Res', 'Huesos', 'kg', 0, true, 252),
('Médula', 'Res', 'Huesos', 'kg', 0, true, 253),
('Tuétano', 'Res', 'Huesos', 'kg', 0, true, 254),
('Hueso de res', 'Res', 'Huesos', 'kg', 0, true, 255),
('Hueso de rodilla', 'Res', 'Huesos', 'kg', 0, true, 256),
('Hueso de aguja', 'Res', 'Huesos', 'kg', 0, true, 257),

-- =========================
-- RES · VÍSCERAS
-- =========================
('Lengua', 'Res', 'Vísceras', 'pieza', 0, true, 201),
('Corazón', 'Res', 'Vísceras', 'kg', 0, true, 202),
('Hígado', 'Res', 'Vísceras', 'kg', 0, true, 203),
('Riñón', 'Res', 'Vísceras', 'kg', 0, true, 204),
('Sesos', 'Res', 'Vísceras', 'kg', 0, true, 205),
('Patas', 'Res', 'Vísceras', 'pieza', 0, true, 206),
('Menudo', 'Res', 'Vísceras', 'kg', 0, true, 207),
('Tripa de res', 'Res', 'Vísceras', 'kg', 0, true, 208),
('Panza de res', 'Res', 'Vísceras', 'kg', 0, true, 209),
('Bofe', 'Res', 'Vísceras', 'kg', 0, true, 210),
('Criadillas', 'Res', 'Vísceras', 'kg', 0, true, 211),
('Ubre', 'Res', 'Vísceras', 'kg', 0, true, 212),
('Ojo', 'Res', 'Vísceras', 'kg', 0, true, 213),

-- =========================
-- RES · GRASA
-- =========================
('Grasa', 'Res', 'Grasa', 'kg', 0, true, 281),
('Grasa molida', 'Res', 'Grasa', 'kg', 0, true, 282),
('Grasa de res', 'Res', 'Grasa', 'kg', 0, true, 283),

-- =========================
-- CERDO · CORTES
-- =========================
('Pierna', 'Cerdo', 'Corte', 'kg', 0, true, 301),
('Pierna deshuesada', 'Cerdo', 'Corte', 'kg', 0, true, 302),
('Lomo', 'Cerdo', 'Corte', 'kg', 0, true, 303),
('Lomo deshuesado', 'Cerdo', 'Corte', 'kg', 0, true, 304),
('Cabeza de lomo', 'Cerdo', 'Corte', 'kg', 0, true, 305),
('Costilla', 'Cerdo', 'Corte', 'kg', 0, true, 306),
('Costillar', 'Cerdo', 'Corte', 'kg', 0, true, 307),
('Espinazo', 'Cerdo', 'Corte', 'kg', 0, true, 308),
('Maciza', 'Cerdo', 'Corte', 'kg', 0, true, 309),
('Chuleta', 'Cerdo', 'Corte', 'kg', 0, true, 310),
('Chuleta ahumada', 'Cerdo', 'Corte', 'kg', 0, true, 311),
('Chamorro', 'Cerdo', 'Corte', 'kg', 0, true, 312),
('Codillo', 'Cerdo', 'Corte', 'kg', 0, true, 313),
('Espaldilla', 'Cerdo', 'Corte', 'kg', 0, true, 314),
('Milanesa de cerdo', 'Cerdo', 'Corte', 'kg', 0, true, 315),
('Bistec de cerdo', 'Cerdo', 'Corte', 'kg', 0, true, 316),
('Molida de cerdo', 'Cerdo', 'Corte', 'kg', 0, true, 317),
('Carne para guisar de cerdo', 'Cerdo', 'Corte', 'kg', 0, true, 318),
('Papada', 'Cerdo', 'Corte', 'kg', 0, true, 319),
('Cachete', 'Cerdo', 'Corte', 'kg', 0, true, 320),
('Chuleta natural', 'Cerdo', 'Corte', 'kg', 0, true, 321),
('Costilla St. Louis', 'Cerdo', 'Corte', 'kg', 0, true, 322),
('Pernil', 'Cerdo', 'Corte', 'kg', 0, true, 323),
('Pierna con hueso', 'Cerdo', 'Corte', 'kg', 0, true, 324),
('Lomo entero', 'Cerdo', 'Corte', 'kg', 0, true, 325),
('Carne para carnitas', 'Cerdo', 'Corte', 'kg', 0, true, 326),
('Carne para cochinita', 'Cerdo', 'Corte', 'kg', 0, true, 327),
('Carne para chicharrón', 'Cerdo', 'Corte', 'kg', 0, true, 328),
('Chuleta con hueso', 'Cerdo', 'Corte', 'kg', 0, true, 329),
('Chuleta sin hueso', 'Cerdo', 'Corte', 'kg', 0, true, 330),
('Milanesa de pierna', 'Cerdo', 'Corte', 'kg', 0, true, 331),
('Milanesa de lomo', 'Cerdo', 'Corte', 'kg', 0, true, 332),
('Molida de cerdo especial', 'Cerdo', 'Corte', 'kg', 0, true, 333),

-- =========================
-- CERDO · EMBUTIDOS
-- =========================
('Longaniza', 'Cerdo', 'Embutido', 'kg', 0, true, 401),
('Chorizo', 'Cerdo', 'Embutido', 'kg', 0, true, 402),
('Chistorra', 'Cerdo', 'Embutido', 'kg', 0, true, 403),
('Adobada', 'Cerdo', 'Embutido', 'kg', 0, true, 404),
('Pastor', 'Cerdo', 'Embutido', 'kg', 0, true, 405),
('Salchicha', 'Cerdo', 'Embutido', 'kg', 0, true, 406),
('Chorizo casero', 'Cerdo', 'Embutido', 'kg', 0, true, 407),
('Longaniza de cerdo', 'Cerdo', 'Embutido', 'kg', 0, true, 408),
('Moronga', 'Cerdo', 'Embutido', 'kg', 0, true, 409),
('Queso de puerco', 'Cerdo', 'Embutido', 'kg', 0, true, 410),
('Chorizo oaxaqueño', 'Cerdo', 'Embutido', 'kg', 0, true, 411),
('Chorizo argentino', 'Cerdo', 'Embutido', 'kg', 0, true, 412),
('Longaniza ahumada', 'Cerdo', 'Embutido', 'kg', 0, true, 413),
('Salchicha para asar', 'Cerdo', 'Embutido', 'kg', 0, true, 414),
('Salchicha roja', 'Cerdo', 'Embutido', 'kg', 0, true, 415),
('Salchicha blanca', 'Cerdo', 'Embutido', 'kg', 0, true, 416),
('Chorizo para asar', 'Cerdo', 'Embutido', 'kg', 0, true, 417),
('Chorizo de Toluca', 'Cerdo', 'Embutido', 'kg', 0, true, 418),
('Chorizo español', 'Cerdo', 'Embutido', 'kg', 0, true, 419),

-- =========================
-- CERDO · GRASA Y MATERIAL
-- =========================
('Tocino', 'Cerdo', 'Grasa', 'kg', 0, true, 451),
('Panceta', 'Cerdo', 'Grasa', 'kg', 0, true, 452),
('Cuero', 'Cerdo', 'Grasa', 'kg', 0, true, 453),
('Manteca', 'Cerdo', 'Grasa', 'kg', 0, true, 454),
('Chicharrón crudo', 'Cerdo', 'Grasa', 'kg', 0, true, 455),
('Cuero de cerdo', 'Cerdo', 'Grasa', 'kg', 0, true, 456),
('Grasa de cerdo', 'Cerdo', 'Grasa', 'kg', 0, true, 457),

-- =========================
-- CERDO · VÍSCERAS Y PARTES
-- =========================
('Cabeza', 'Cerdo', 'Vísceras', 'pieza', 0, true, 501),
('Oreja', 'Cerdo', 'Vísceras', 'pieza', 0, true, 502),
('Hocico', 'Cerdo', 'Vísceras', 'pieza', 0, true, 503),
('Patitas', 'Cerdo', 'Vísceras', 'pieza', 0, true, 504),
('Manitas', 'Cerdo', 'Vísceras', 'pieza', 0, true, 505),
('Hígado', 'Cerdo', 'Vísceras', 'kg', 0, true, 506),
('Corazón', 'Cerdo', 'Vísceras', 'kg', 0, true, 507),
('Riñón', 'Cerdo', 'Vísceras', 'kg', 0, true, 508),
('Tripa de cerdo', 'Cerdo', 'Vísceras', 'kg', 0, true, 509),
('Panza de cerdo', 'Cerdo', 'Vísceras', 'kg', 0, true, 510),
('Lengua de cerdo', 'Cerdo', 'Vísceras', 'pieza', 0, true, 511),
('Sesos de cerdo', 'Cerdo', 'Vísceras', 'kg', 0, true, 512),
('Bofe de cerdo', 'Cerdo', 'Vísceras', 'kg', 0, true, 513),

-- =========================
-- OBRADOR
-- =========================
('Chorizo rojo', 'Cerdo', 'Obrador', 'kg', 0, true, 601),
('Chorizo verde', 'Cerdo', 'Obrador', 'kg', 0, true, 602),
('Longaniza natural', 'Cerdo', 'Obrador', 'kg', 0, true, 603),
('Longaniza enchilada', 'Cerdo', 'Obrador', 'kg', 0, true, 604),
('Alambre', 'Res', 'Obrador', 'kg', 0, true, 605),
('Arrachera marinada', 'Res', 'Obrador', 'kg', 0, true, 606),
('Carne enchilada', 'Res', 'Obrador', 'kg', 0, true, 607),
('Carne al pastor', 'Cerdo', 'Obrador', 'kg', 0, true, 608),
('Carne para tacos', 'Res', 'Obrador', 'kg', 0, true, 609),
('Carne para hamburguesa', 'Res', 'Obrador', 'kg', 0, true, 610),
('Hamburguesas', 'Res', 'Obrador', 'paquete', 0, true, 611),
('Albóndigas', 'Res', 'Obrador', 'kg', 0, true, 612),
('Brochetas', 'Res', 'Obrador', 'pieza', 0, true, 613),
('Chicharrón prensado', 'Cerdo', 'Obrador', 'kg', 0, true, 614),
('Chicharrón preparado', 'Cerdo', 'Obrador', 'kg', 0, true, 615),
('Cecina enchilada', 'Res', 'Obrador', 'kg', 0, true, 616),
('Carne machaca', 'Res', 'Obrador', 'kg', 0, true, 617),
('Chorizo parrillero', 'Cerdo', 'Obrador', 'kg', 0, true, 618),
('Carne para burritos', 'Res', 'Obrador', 'kg', 0, true, 619),
('Pierna adobada', 'Cerdo', 'Obrador', 'kg', 0, true, 620),
('Costilla adobada', 'Cerdo', 'Obrador', 'kg', 0, true, 621),
('Chamorro adobado', 'Cerdo', 'Obrador', 'kg', 0, true, 622),
('Carnitas', 'Cerdo', 'Obrador', 'kg', 0, true, 623),
('Cochinita pibil', 'Cerdo', 'Obrador', 'kg', 0, true, 624),
('Barbacoa de res', 'Res', 'Obrador', 'kg', 0, true, 625),
('Tasajo', 'Res', 'Obrador', 'kg', 0, true, 626),
('Cecina adobada', 'Res', 'Obrador', 'kg', 0, true, 627),
('Carne deshebrada', 'Res', 'Obrador', 'kg', 0, true, 628),
('Carne para flautas', 'Res', 'Obrador', 'kg', 0, true, 629),
('Carne para sopes', 'Res', 'Obrador', 'kg', 0, true, 630),
('Carne para gorditas', 'Res', 'Obrador', 'kg', 0, true, 631),
('Carne para torta', 'Res', 'Obrador', 'kg', 0, true, 632),
('Milanesa empanizada', 'Res', 'Obrador', 'kg', 0, true, 633),
('Milanesa de res', 'Res', 'Obrador', 'kg', 0, true, 634),
('Milanesa de cerdo empanizada', 'Cerdo', 'Obrador', 'kg', 0, true, 635),
('Chorizo con queso', 'Cerdo', 'Obrador', 'kg', 0, true, 636),
('Chorizo con jalapeño', 'Cerdo', 'Obrador', 'kg', 0, true, 637),
('Longaniza de jalapeño', 'Cerdo', 'Obrador', 'kg', 0, true, 638),
('Chistorra ahumada', 'Cerdo', 'Obrador', 'kg', 0, true, 639),
('Chicharrón en salsa', 'Cerdo', 'Obrador', 'kg', 0, true, 640),
('Chicharrón de cerdo', 'Cerdo', 'Obrador', 'kg', 0, true, 641),
('Chicharrón de res', 'Res', 'Obrador', 'kg', 0, true, 642),
('Albóndigas en chipotle', 'Res', 'Obrador', 'kg', 0, true, 643),
('Brochetas de res', 'Res', 'Obrador', 'pieza', 0, true, 644),
('Brochetas de cerdo', 'Cerdo', 'Obrador', 'pieza', 0, true, 645),
('Hamburguesas de res', 'Res', 'Obrador', 'paquete', 0, true, 646),
('Hamburguesas de cerdo', 'Cerdo', 'Obrador', 'paquete', 0, true, 647),
('Carne para pozole', 'Cerdo', 'Obrador', 'kg', 0, true, 648),
('Carne para menudo', 'Res', 'Obrador', 'kg', 0, true, 649),
('Pierna rellena', 'Cerdo', 'Obrador', 'pieza', 0, true, 650);
